import type { Category, Item } from "@/lib/types";

export const categories: Category[] = [
  { slug: "coding", name: "Coding", description: "Programação e desenvolvimento." },
  { slug: "ai", name: "AI", description: "Modelos, LLMs e IA." },
  { slug: "design", name: "Design", description: "Design e UX." },
  { slug: "automation", name: "Automation", description: "Automação e integrações." },
  { slug: "data", name: "Data", description: "Dados e analytics." },
  { slug: "productivity", name: "Productivity", description: "Produtividade pessoal." },
  { slug: "business", name: "Business", description: "Negócios e gestão." },
  { slug: "research", name: "Research", description: "Pesquisa e aprendizado." },
];

export const items: Item[] = [
  {
    id: "1",
    name: "Claude Code",
    slug: "claude-code",
    description: "CLI agentic para desenvolvimento de software direto no terminal.",
    type: "Agent",
    category: "coding",
    source: "Claude Code",
    repositoryUrl: "https://github.com/anthropics/claude-code",
    websiteUrl: "https://claude.com/claude-code",
    documentationUrl: "https://code.claude.com/docs",
    notes:
      "Testei para geração de código.\n\nPontos fortes:\n- rápido\n- entende o repositório inteiro\n\nPontos fracos:\n- consumo de tokens alto em tarefas longas\n\nUsaria novamente:\nSim",
    rating: 5,
    status: "Approved",
    tags: ["cli", "agente", "terminal"],
    favorite: true,
    relationships: [{ label: "Alternativa de", itemSlug: "openhands", itemName: "OpenHands" }],
    createdAt: "2026-06-02T10:00:00.000Z",
    updatedAt: "2026-08-20T14:30:00.000Z",
  },
  {
    id: "2",
    name: "OpenHands",
    slug: "openhands",
    description: "Plataforma open-source para agentes de desenvolvimento autônomos.",
    type: "Agent",
    category: "coding",
    source: "GitHub",
    repositoryUrl: "https://github.com/All-Hands-AI/OpenHands",
    notes: "Explorei rapidamente via vídeo. Ainda não testei localmente.",
    rating: 3,
    status: "Discovered",
    tags: ["agente", "open-source"],
    favorite: false,
    relationships: [{ label: "Alternativa de", itemSlug: "claude-code", itemName: "Claude Code" }],
    createdAt: "2026-07-14T09:15:00.000Z",
    updatedAt: "2026-07-14T09:15:00.000Z",
  },
  {
    id: "3",
    name: "n8n",
    slug: "n8n",
    description: "Ferramenta de automação de workflows com nós visuais.",
    type: "Tool",
    category: "automation",
    source: "YouTube",
    websiteUrl: "https://n8n.io",
    notes:
      "Usei para automatizar envio de relatórios.\n\nPontos fortes:\n- muitos integradores prontos\n\nPontos fracos:\n- curva de aprendizado nos nós mais avançados\n\nUsaria novamente:\nSim",
    rating: 4,
    status: "Approved",
    tags: ["automação", "workflow", "self-hosted"],
    favorite: true,
    relationships: [{ label: "Integra com", itemSlug: "supabase", itemName: "Supabase" }],
    createdAt: "2026-05-20T11:00:00.000Z",
    updatedAt: "2026-08-01T16:45:00.000Z",
  },
  {
    id: "4",
    name: "Supabase",
    slug: "supabase",
    description: "Backend as a service com Postgres, auth e storage.",
    type: "Tool",
    category: "data",
    source: "GitHub",
    repositoryUrl: "https://github.com/supabase/supabase",
    websiteUrl: "https://supabase.com",
    notes: "Base de dados e auth do próprio Personal AI Hub a partir da Fase 3.",
    rating: 5,
    status: "Approved",
    tags: ["banco de dados", "backend", "postgres"],
    favorite: true,
    relationships: [{ label: "Integra com", itemSlug: "n8n", itemName: "n8n" }],
    createdAt: "2026-04-10T08:30:00.000Z",
    updatedAt: "2026-08-25T12:00:00.000Z",
  },
  {
    id: "5",
    name: "v0",
    slug: "v0",
    description: "Gerador de interfaces React a partir de prompts, feito pela Vercel.",
    type: "Tool",
    category: "design",
    source: "LinkedIn",
    websiteUrl: "https://v0.app",
    notes: "Testando para prototipagem rápida de telas.",
    rating: 4,
    status: "Testing",
    tags: ["ui", "prototipagem"],
    favorite: false,
    relationships: [],
    createdAt: "2026-08-05T13:20:00.000Z",
    updatedAt: "2026-08-28T09:10:00.000Z",
  },
  {
    id: "6",
    name: "Perplexity",
    slug: "perplexity",
    description: "Motor de busca com respostas geradas por IA e citações.",
    type: "Tool",
    category: "research",
    source: "Reddit",
    websiteUrl: "https://perplexity.ai",
    notes: "Bom para pesquisas rápidas com fontes. Substituiu parte das minhas buscas no Google.",
    rating: 4,
    status: "Approved",
    tags: ["busca", "pesquisa"],
    favorite: false,
    relationships: [],
    createdAt: "2026-03-18T15:40:00.000Z",
    updatedAt: "2026-07-30T10:00:00.000Z",
  },
  {
    id: "7",
    name: "SKILL.md spec",
    slug: "skill-md-spec",
    description: "Convenção de arquivo para definir skills reutilizáveis por agentes.",
    type: "Resource",
    category: "ai",
    source: "Claude Code",
    documentationUrl: "https://code.claude.com/docs/en/skills",
    notes: "Referência para estruturar skills próprias. Ainda estudando padrões de uso.",
    rating: 0,
    status: "Discovered",
    tags: ["skills", "documentação"],
    favorite: false,
    relationships: [],
    createdAt: "2026-08-22T17:00:00.000Z",
    updatedAt: "2026-08-22T17:00:00.000Z",
  },
  {
    id: "8",
    name: "Notion AI",
    slug: "notion-ai",
    description: "Recursos de IA embutidos no Notion para escrita e resumo.",
    type: "Tool",
    category: "productivity",
    source: "Indicação",
    websiteUrl: "https://notion.so",
    notes: "Testei para resumir reuniões. Achei genérico demais comparado a alternativas dedicadas.",
    rating: 2,
    status: "Archived",
    tags: ["notas", "resumo"],
    favorite: false,
    relationships: [],
    createdAt: "2026-02-11T12:00:00.000Z",
    updatedAt: "2026-05-02T12:00:00.000Z",
  },
];

export const recentItems = [...items].sort(
  (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(),
);

export const favoriteItems = items.filter((item) => item.favorite);

export function getCategory(slug: Item["category"]) {
  return categories.find((category) => category.slug === slug);
}

export function itemCountByCategory(slug: Item["category"]) {
  return items.filter((item) => item.category === slug).length;
}

export function getItemBySlug(slug: string) {
  return items.find((item) => item.slug === slug);
}
